services:
  minio1:
    image: minio/minio:latest
    hostname: minio1
    expose:
      - "9000"
      - "9090"
    ports:
      - "9000:9000" #server
      - "9090:9090" #admin
    environment:
      - MINIO_ROOT_USER=access-key
      - MINIO_ROOT_PASSWORD=secret-access-key
      - MINIO_VOLUMES=/mnt/data
      # - MINIO_CONFIG_ENV_FILE=/etc/config.env
    volumes:
      # - ./minio_config.env:/etc/config.env # attach minio config file
      - blob_data:/mnt/data # attach docker volumeNamed 
      - blob_data:/data
    command: server --console-address ":9090"

  postgres:
    image: postgres:alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - user_data:/var/lib/postgresql/data

volumes:
  blob_data:
  user_data:
