// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.12.4
// source: internal/blob/storagepb/put_object_response.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ObjectInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutObjectResponse) Reset() {
	*x = PutObjectResponse{}
	mi := &file_internal_blob_storagepb_put_object_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutObjectResponse) ProtoMessage() {}

func (x *PutObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_blob_storagepb_put_object_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutObjectResponse.ProtoReflect.Descriptor instead.
func (*PutObjectResponse) Descriptor() ([]byte, []int) {
	return file_internal_blob_storagepb_put_object_response_proto_rawDescGZIP(), []int{0}
}

func (x *PutObjectResponse) GetInfo() *ObjectInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_internal_blob_storagepb_put_object_response_proto protoreflect.FileDescriptor

var file_internal_blob_storagepb_put_object_response_proto_rawDesc = []byte{
	0x0a, 0x31, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x6c, 0x6f, 0x62, 0x2f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x70, 0x62, 0x2f, 0x70, 0x75, 0x74, 0x5f, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x70, 0x62, 0x1a, 0x29,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x6c, 0x6f, 0x62, 0x2f, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x70, 0x62, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x11, 0x50, 0x75, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x70, 0x62, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x1b, 0x5a, 0x19, 0x2e, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x6c, 0x6f, 0x62, 0x2f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_blob_storagepb_put_object_response_proto_rawDescOnce sync.Once
	file_internal_blob_storagepb_put_object_response_proto_rawDescData = file_internal_blob_storagepb_put_object_response_proto_rawDesc
)

func file_internal_blob_storagepb_put_object_response_proto_rawDescGZIP() []byte {
	file_internal_blob_storagepb_put_object_response_proto_rawDescOnce.Do(func() {
		file_internal_blob_storagepb_put_object_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_blob_storagepb_put_object_response_proto_rawDescData)
	})
	return file_internal_blob_storagepb_put_object_response_proto_rawDescData
}

var file_internal_blob_storagepb_put_object_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_blob_storagepb_put_object_response_proto_goTypes = []any{
	(*PutObjectResponse)(nil), // 0: storagepb.PutObjectResponse
	(*ObjectInfo)(nil),        // 1: storagepb.ObjectInfo
}
var file_internal_blob_storagepb_put_object_response_proto_depIdxs = []int32{
	1, // 0: storagepb.PutObjectResponse.info:type_name -> storagepb.ObjectInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_blob_storagepb_put_object_response_proto_init() }
func file_internal_blob_storagepb_put_object_response_proto_init() {
	if File_internal_blob_storagepb_put_object_response_proto != nil {
		return
	}
	file_internal_blob_storagepb_object_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_blob_storagepb_put_object_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_blob_storagepb_put_object_response_proto_goTypes,
		DependencyIndexes: file_internal_blob_storagepb_put_object_response_proto_depIdxs,
		MessageInfos:      file_internal_blob_storagepb_put_object_response_proto_msgTypes,
	}.Build()
	File_internal_blob_storagepb_put_object_response_proto = out.File
	file_internal_blob_storagepb_put_object_response_proto_rawDesc = nil
	file_internal_blob_storagepb_put_object_response_proto_goTypes = nil
	file_internal_blob_storagepb_put_object_response_proto_depIdxs = nil
}
