package main

const (
	BLOB_MINIO_ENDPOINT          = "BLOB_MINIO_ENDPOINT"
	BLOB_MINIO_ACCESS_KEY        = "BLOB_MINIO_ACCESS_KEY"
	BLOB_MINIO_SECRET_ACCESS_KEY = "BLOB_MINIO_SECRET_ACCESS_KEY"

	USER_PG_URI = "USER_PG_URI"

	TOKEN_REDIS_URI = "TOKEN_REDIS_URI"

	SESSION_REDIS_URI = "SESSION_REDIS_URI"
)
